Modeler v5 compatibility
FlowSquad/camunda-modeler-i18n-plugin pull request #13
Opened 2023-01-26 15:08 UTC by rami-nk

Fixed language selection dropdown according to https://camunda.com/blog/2022/01/how-to-migrate-your-camunda-modeler-plugins-to-work-with-camunda-modeler-5-x/.
Modal is still used instead of Overlay component.

During the migration missing translation keys were noticed.
Below is the list of the missing translations keys.

Missing translation: Compensation
Missing translation: Link
Missing translation: Multi-instance
Missing translation: Timer
Missing translation: History cleanup
Missing translation: Tasklist
Missing translation: Candidate starter
Missing translation: External task
Missing translation: Process variables
Missing translation: User assignment
Missing translation: Form fields
Missing translation: Task listeners
Missing translation: Start initiator
Missing translation: Called element
Missing translation: Asynchronous continuations
Missing translation: Job execution
Missing translation: In mapping propagation
Missing translation: In mappings
Missing translation: Inputs
Missing translation: Connector inputs
Missing translation: Out mapping propagation
Missing translation: Out mappings
Missing translation: Outputs
Missing translation: Connector outputs
Missing translation: Execution listeners
Missing translation: Extension properties
Missing translation: Field injections
Missing translation: Business key
Missing translation: Version tag
Missing translation: Element documentation
Missing translation: Time to live
Missing translation: Candidate starter groups
Missing translation: Candidate starter users

2023-01-27 17:04 UTC, alex-praschek approved these changes

2023-01-27 17:04 UTC, alex-praschek commented on README.md
>  This plugin allows you to translate the UI of the Camunda Modeler. It contains translations for German, English and Portuguese and can be easily extended or customized.
Chinese (Traditional), Chinese (Simplified), Dutch, and Russian are missing in the description. Could you update this please?

2023-01-30 08:24 UTC, rami-nk commented
I've updated README.md and added German translations for the missing keys.

2023-01-30 12:14 UTC, alex-praschek approved these changes
Please align with @dominikhorn93 about the translations marked as TODO. Thanks!

2023-01-31 08:44 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Camunda Forms': 'Camunda Formen',
Camunda Formulare

2023-01-31 08:46 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Candidate starter': 'Kandidatenstarter', // TODO
würde ich nicht übersetzen

2023-01-31 08:47 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Called element': 'Aufgerufenes Element', // TODO
// TODO löschen

2023-01-31 08:47 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Asynchronous continuations': 'Asynchrone Fortsetzung', // TODO
// TODO löschen

2023-01-31 08:48 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Inputs': 'Eingaben',
Inputs würde ich nicht übersetzen

2023-01-31 08:48 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Outputs': 'Ausgaben',
Outputs würde ich nicht übersetzen

2023-01-31 08:49 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Extension properties': 'Zusätzliche Eigenschaften', // TODO
//TODO entfernen

2023-01-31 08:49 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Form key': 'Form-Key',
Formular Key

2023-01-31 08:49 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Form reference': 'Form-Referenz'
Formular Referenz

2023-01-31 08:55 UTC, dominikhorn93 commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'External task': 'Exterer Task',
Externer

2023-01-31 08:56 UTC, dominikhorn93 requested changes
Danke dafür!
Habe ein paar Änderungen vorgeschlagen

2023-01-31 09:19 UTC, alex-praschek commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Camunda Forms': 'Camunda Formen',
Würde das nicht übersetzen, ist ein Eigenname

2023-01-31 09:20 UTC, alex-praschek commented on client/bpmnjs-i18n-extension/languages/de/properties-panel.js
> +    'Form key': 'Form-Key',
Formular-Key

2023-02-08 10:09 UTC, dominikhorn93 approved these changes

2023-02-08 10:37 UTC, merged